name: PR
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn
      - run: yarn lint
  deploy:
    name: Deploy (TEST)
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: vercel -n 'timetab' -c -t ${{ secrets.VERCEL_TOKEN }}
